# Generated by Django 5.1.15 on 2026-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improvements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="benefit_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sec", "SEÇ (Sağlık-Emniyet-Çevre)"),
                    ("kaizen", "A3 Kaizen / Kobetsu Kaizen"),
                    ("respect", "İnsana Saygı"),
                    ("reasonable", "Makul Öneri"),
                    ("autonomous", "Otonom Bakım"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="cost_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="estimated_benefit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="problem",
            field=models.TextField(blank=True, help_text="Mevcut durum / problem"),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="solution",
            field=models.TextField(blank=True, help_text="Çözüm önerisi"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
