# Generated by Django 5.1.15 on 2026-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("improvements", "0002_suggestion_benefit_note_suggestion_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("five_s", "5S"),
                    ("sec", "SEÇ (Sağlık-Emniyet-Çevre)"),
                    ("respect", "İnsana Saygı"),
                    ("sigma_green", "6 Sigma Yeşil Kuşak"),
                    ("sigma_black", "6 Sigma Kara Kuşak"),
                    ("kaizen", "A3 Kaizen / Kobetsu Kaizen"),
                    ("investment", "Yatırım"),
                    ("reasonable", "Makul Öneri"),
                    ("asakai_card", "Asakai / Çözüm Kartı"),
                    ("tnd", "TND (Tek Nokta Dersi)"),
                    ("autonomous", "Otonom Bakım"),
                    ("rnd", "Ar-Ge"),
                    ("innovation", "İnovasyon"),
                    ("poka_yoke", "Poka Yoke"),
                ],
                max_length=20,
            ),
        ),
    ]
