# Generated by Django 5.1.15 on 2026-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi",
            name="template_key",
            field=models.CharField(
                blank=True,
                help_text="Set when created from a built-in template; lets other modules find and auto-feed this KPI (e.g. implemented_suggestions).",
                max_length=50,
            ),
        ),
    ]
