# Generated by Django 5.1.15 on 2026-09-04 15:36

import apps.beforeafter.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeforeAfterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("capacity", "Kapasite Kazancı"),
                            ("labor", "İş Gücü Kazancı"),
                            ("energy", "Enerji Kazancı"),
                            ("space", "Alan Kazancı"),
                            ("material", "Malzeme Kazancı"),
                            ("stock_transport", "Stok/Taşıma"),
                            ("scrap_rework", "Hurda/Yeniden İşlem"),
                            ("quality", "Kalite"),
                            ("safety", "İSG"),
                            ("environment", "Çevre"),
                            ("ergonomics", "Ergonomi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("problem", models.TextField(blank=True)),
                (
                    "before_note",
                    models.TextField(blank=True, help_text="ÖNCE açıklama"),
                ),
                (
                    "after_note",
                    models.TextField(blank=True, help_text="SONRA açıklama"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("cost_note", models.TextField(blank=True, help_text="Maliyet hesabı")),
                ("budget_code", models.CharField(blank=True, max_length=200)),
                (
                    "gain_continuity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("continuous", "Sürekli"),
                            ("one_time", "Tek Seferlik"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "one_time_gain",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("gain_note", models.TextField(blank=True, help_text="Kazanç hesabı")),
                (
                    "gain_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("capacity", "Kapasite Kazancı"),
                            ("labor", "İş Gücü Kazancı"),
                            ("energy", "Enerji Kazancı"),
                            ("space", "Alan Kazancı"),
                            ("material", "Malzeme Kazancı"),
                            ("stock_transport", "Stok/Taşıma"),
                            ("scrap_rework", "Hurda/Yeniden İşlem"),
                            ("quality", "Kalite"),
                            ("safety", "İSG"),
                            ("environment", "Çevre"),
                            ("ergonomics", "Ergonomi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="before_after_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="before_after_forms",
                        to="processes.process",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BeforeAfterPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("before", "Önce"), ("after", "Sonra")], max_length=6
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.beforeafter.models.before_after_photo_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="beforeafter.beforeafterform",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "id"],
            },
        ),
    ]
