# Generated by Django 5.1.15 on 2026-09-03 21:49

import apps.audits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.audits.models.finding_photo_path
            ),
        ),
    ]
