# Generated by Django 5.1.15 on 2026-09-04 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_alter_finding_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="checklist_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Default question set used when auditing this area",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="areas",
                to="audits.checklisttemplate",
            ),
        ),
    ]
