# Generated by Django 5.1.15 on 2026-09-04 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_area_checklist_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_type",
            field=models.CharField(
                choices=[("internal", "İç Denetim"), ("external", "Dış Denetim")],
                default="internal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated from area + template when empty",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_audits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
