# Generated by Django 5.1.15 on 2026-09-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_audit_audit_type_audit_name_audit_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="audit_type",
            field=models.CharField(
                choices=[
                    ("announced", "Haberli Denetim"),
                    ("unannounced", "Habersiz Denetim"),
                ],
                default="announced",
                max_length=12,
            ),
        ),
    ]
