# Generated by Django 5.1.15 on 2026-09-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="asakai_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="meetings.asakaiitem",
            ),
        ),
    ]
