# Generated by Django 5.1.15 on 2026-09-04 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnePointLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "Temel Bilgi"),
                            ("problem", "Problem Vakası"),
                            ("improvement", "İyileştirme Örneği"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "topic",
                    models.CharField(help_text="Eğitimin konusu", max_length=200),
                ),
                ("content", models.TextField(blank=True, help_text="Eğitimin içeriği")),
                ("held_at", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=15, help_text="Süre (dakika)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attended_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="processes.process",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        help_text="Eğitim veren",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-held_at", "-id"],
            },
        ),
    ]
