# Generated by Django 5.1.15 on 2026-09-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onepointlesson",
            name="category",
            field=models.CharField(
                choices=[
                    ("employee_satisfaction", "Çalışan Memnuniyeti"),
                    ("maintenance", "Bakım Onarım"),
                    ("quality", "Kalite"),
                    ("new_product", "Yeni Ürün"),
                    ("new_process", "Yeni Proses"),
                    ("kaizen", "Kaizen"),
                    ("five_s", "5S"),
                    ("poka_yoke", "Poka-Yoke"),
                    ("competency", "Yetkinlik"),
                    ("motivation", "Motivasyon"),
                    ("hse", "İSG"),
                    ("capacity_gain", "Kapasite Kazancı"),
                    ("labor_gain", "İş Gücü Kazancı"),
                    ("energy_gain", "Enerji Kazancı"),
                    ("space_gain", "Alan Kazancı"),
                    ("material_gain", "Malzeme Kazancı"),
                    ("ergonomics", "Ergonomi"),
                    ("customer_satisfaction", "Müşteri Memnuniyeti"),
                    ("environment", "Çevre"),
                    ("stock_transport", "Stok/Taşıma"),
                    ("scrap_rework", "Hurda/Yeniden İşlem"),
                ],
                max_length=30,
            ),
        ),
    ]
